version: "3.8"
services:
  inventorydb:
    container_name: inventorydb
    restart: always
    ports:
      - "1440:1433"
    volumes:
      - inventorydb_volume:/data/db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12*
  orderdb:
    container_name: orderdb
    restart: always
    ports:
      - "1441:1433"
    volumes:
      - orderdb_volume:/data/db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12*
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "1442:1433"
    volumes:
      - basketdb_volume:/data/db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12*
  identitydb:
    container_name: identitydb
    restart: always
    ports:
      - "1443:1433"
    volumes:
      - identitydb_volume:/data/db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12*
  inventory.api:
    container_name: inventory.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Default=Server=inventorydb;Database=InventoryDb;User=sa;Password=Password12*;TrustServerCertificate=True"
    ports:
      - "5011:80"
    depends_on:
      - inventorydb
  identityserver.api:
    container_name: identityserver.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Default=Server=identitydb;Database=identitydb;User=sa;Password=Password12*;TrustServerCertificate=True"
    ports:
      - "5001:80"
    depends_on:
      - identitydb
  order.api:
    container_name: order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Default=Server=orderdb;Database=orderdb;User=sa;Password=Password12*;TrustServerCertificate=True"
    ports:
      - "5015:80"
    depends_on:
      - orderdb
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Default=Server=basketdb;Database=basketdb;User=sa;Password=Password12*;TrustServerCertificate=True"
    ports:
      - "5013:80"
    depends_on:
      - basketdb
  gateway.api:
    container_name: gateway.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:80"